RascalSoftware/python-RAT

- RAT/classlist.py
- RAT/project.py
- tests/test_classlist.py
- tests/test_project.py
- tests/utils.py
We add the ability to:
- set an item in the ClassList using an object
- determine the class handle by ensuring "isinstance" is true for all elements (allows ProtectedParameters to be included correctly.)
- iadd and extend the ClassList with the expected behaviour for individual objects.
> Adds new features to ClassList

- requirements.txt
- tests/test_controls.py
> Updated pydantic to 2.4.0

- RAT/events.py
- cpp/rat.cpp
- tests/test_events.py
- Updates output structure
- Add progress event
> Updates C++ backend and rat_core extension

- RATapi/models.py
- tests/test_project.py
Fixes #56 : A `NotImplementedError` is now raised if the user attempts to add a data or function background, as these backgrounds are not yet supported. I've also set Pytest to skip tests that use these backgrounds - if it's a better idea to remove them entirely then I will do that instead.
>  raises NotImplementedError for data/function backgrounds 

- RATapi/utils/plotting.py
- requirements.txt
- setup.py
- tests/test_plotting.py
This PR fixes #45 by adding the remaining plotting functionality from RAT to the Python API. These are:
- `cornerPlot` -> `plot_corner`
- `plotHists` -> `plot_hists`
- `bayesShadedPlot` -> new `bayes` parameter for `plot_ref_sld`
- `histp` -> `plot_one_hist` (with `estimated_density` parameter for estimated density overplot)
- `mcmcplot` -> `plot_chain`
- `plotBayes` -> `plot_bayes` (just calls `plot_ref_sld` with and without confidence intervals, `plot_hists` and `plot_corner`)
> Adds Bayesian plots to Python

- RATapi/run.py
- requirements.txt
- setup.py
- tests/test_run.py
The progress bar will show up for dream runs when display is on
```
controls = RAT.Controls()
controls.procedure = 'dream'
#controls.display = 'off'
problem, results = RAT.run(problem, controls)
```
> Adds progress bar which uses the progress event

- RATapi/controls.py
- pyproject.toml
- tests/test_controls.py
This PR changes the Control parameter `nMCMC` to an int. It is currently a `float` greater than or equal to zero, but if you set it to a non-integer value then the process hangs (because it is supposed to be an integer). It is a float in the C++ code, and `pybind11` automatically converts the integer to a float when the C++ Controls object is made: to test this you can try
```python
from RATapi.inputs import make_input
_, _, _, _, cpp_controls = make_input(problem, RAT.Controls(procedure="ns"))
print(cpp_controls.nMCMC)
```
and see that it prints 0.0.
Also fixes ruff linting as the latest ruff update made it lint jupyter notebooks by default.
> Changes control parameter `nMCMC` to int & fixes failing ruff lint

- cpp/rat.cpp
- tests/test_events.py
- tests/test_inputs.py
> Makes the arguments from RAT_main and events data pickleable

- RATapi/controls.py
- RATapi/examples/absorption/absorption.py
- RATapi/inputs.py
- cpp/rat.cpp
- setup.py
- tests/test_controls.py
- tests/test_inputs.py
Fixes #69 by splitting `resampleParams` into `resampleMinAngle` and `resampleNPoints`. Also changes the validation for `resampleMinAngle` to match MATLAB and be mathematically sensible - now accepts values strictly greater than 0 and less than or equal to 1.
> Splits `resampleParams` into two parameters and bumps version to 0.0.0.dev2

- RATapi/classlist.py
- tests/test_classlist.py
This PR refactors the `ClassList._check_classes` and `ClassList._check_unique_name_fields` routines to provide better error messages, specifically including the indices of the bad input in the input lists. This may help with mitigating the coercion issue identified in #79 alongside giving better information for bad input to routines that mutate ClassLists.
I'm open to input about the format of the error messages.
> Improves error messages for ClassLists

- RATapi/inputs.py
- cpp/rat.cpp
- tests/test_inputs.py
I missed this in the PR to make the pybind classes pickleable. The function handles cannot be pickled so this defers the creation of the handles. The script below uses the languages example to test that all 3 languages pickle correctly and run in a process
```
from multiprocessing import Process
def f(problem_definition, cells, limits, priors, cpp_controls):
start = time.time()
problem_definition, output_results, bayes_results = RAT.rat_core.RATMain(
problem_definition,
cells,
limits,
cpp_controls,
priors,
)
end = time.time()
print(f"Run time is: {end-start}s\n")
if __name__ == '__main__':
project = setup_problem.make_example_problem()
controls = RAT.Controls()
problem_definition, cells, limits, priors, cpp_controls = RAT.inputs.make_input(project, controls)
p = Process(target=f, …
```
> Modifies cells to make function handles pickleable

- .github/workflows/run_tests.yml
- RATapi/utils/plotting.py
Addresses https://github.com/RascalSoftware/RAT/issues/266 for the python api
> Adds options to plot_ref_sld

- .github/workflows/build_wheel.yml
- .github/workflows/run_tests.yml
- tests/test_project.py
Added a workaround for MacOS runner ignoring the given python version for the test and fixed a test that was failing on 3.13. The python version is still capped at 3.12 because ubuntu and windows runner are still stuck at 3.12
> Fixes failing test on python 3.13 and ensure macOS uses 3.12

- RATapi/events.py
- RATapi/examples/extras/two_contrast_example.py
- RATapi/utils/convert.py
- RATapi/wrappers.py
- tests/test_inputs.py
Linting failed due to update to ruff.
> Fixes lint failing on runner and adds example for user guide

- cpp/rat.cpp
Could you please confirm the following:
- On the current `main`, the results for the examples contains an array `fitNames` of length >=1, and an array `fitParams` of length 1.
- On this branch, the length of `fitParams` is always the same as that of `fitNames`.
> Fixes bug where "fitParams" outputs only one value

- cpp/rat.cpp
Reverts RascalSoftware/python-RAT#101
> Revert "Fixes bug where "fitParams" outputs only one value"

- RATapi/examples/convert_rascal_project/convert_rascal.py
- RATapi/utils/convert.py
- tests/test_convert.py
Fixes #102, fixes #106. Also adds new tests to test the conversion with both pathlib and strings.
> Fixes converter path bug and makes conversion example portable

- RATapi/classlist.py
- RATapi/controls.py
- RATapi/examples/languages/run_custom_file_languages.py
- RATapi/models.py
- RATapi/project.py
- RATapi/run.py
- RATapi/utils/plotting.py
- tests/test_controls.py
- tests/test_convert.py
- tests/test_models.py
- tests/test_project.py
`ruff` 0.90 added some new rules to the formatter. This PR re-formats the codebase in line with these changes.
> Updates ruff formatting to ruff 0.9

- RATapi/outputs.py
- cpp/rat.cpp
- tests/conftest.py
- tests/test_outputs.py
Reflects RascalSoftware/RAT#304 in the Python
> Adds uncertainty to nested sampler output

- RATapi/outputs.py
- RATapi/utils/plotting.py
Fixes #130 by adding docstrings to the dataclasses in `outputs.py`. Also fixes #128 by fixing the docstring of `plot_bayes`.
> Adds docstrings to the Results struct

- .gitignore
- RATapi/project.py
- tests/test_project.py
Fixes #126 by changing the `Project.save` method to do the following:
- Now only takes one parameter, `filepath`, which is the path to the actual file to save to
- Saves custom file paths relative to where the project is saved and loads them accordingly, so that projects are more portable
> Improves `Project.save`

- MANIFEST.in
- RATapi/utils/plotting.py
- RATapi/wrappers.py
- cpp/includes/defines.h
- cpp/includes/functions.h
- cpp/rat.cpp
- setup.py
- tests/test_plotting.py
- tests/test_wrappers.py
> Adds some docstring to pybind function and some refactors

- RATapi/__init__.py
Fixes a bad import which made orsopy not actually optional.
> Makes orsopy actually optional

- RATapi/controls.py
- tests/test_controls.py
See RascalSoftware/RAT#376 - DREAM crashes if `nChains` is 1 because it requires multiple chains.
> Ensure nChains is greater than 1

- RATapi/controls.py
Fixes the `nSamples` docstring. I got mixed up between something in Vrugt's paper and something in the code when writing it, sorry!
> Fixes the `nSamples` docstring

- RATapi/examples/convert_rascal_project/convert_rascal.py
- RATapi/inputs.py
- RATapi/outputs.py
- RATapi/utils/convert.py
- RATapi/utils/plotting.py
- cpp/includes/defines.h
- cpp/rat.cpp
- tests/conftest.py
- tests/test_convert.py
- tests/test_inputs.py
- tests/test_plotting.py
- tests/test_run.py
Note that the type of `repeatLayers` and the signature of `makeSLDProfile` changed in RascalSoftware/RAT#383
> Updates submodule

- RATapi/utils/plotting.py
Currently, the chain plots crash if `maxpoints` is larger than the length of the chain. This is because we use a `skip` variable:
`skip = floor(nsimulations / maxpoints)`
which gives us spacing so that the sampled points in the plot are evenly distributed across the chain. However, if `nsimulations < maxpoints`, then `skip` will be 0, which causes a crash when we try to use it for a range skip.
We fix this by replacing the above line with
`skip = max(floor(nsimulations / maxpoints), 1)`
so that `skip` is set to 1 (i.e. the entire chain is plotted) when `nsimulations < maxpoints`.
To reproduce:
```python
import RATapi as RAT
project, _ = RAT.examples.DSPC_standard_layers()
controls = RAT.Controls(procedure="dream", nSamples=1000)
_, results = RAT.run(project, controls) …
```
> Fix chain plots crash if chains are smaller than `maxpoints`

- RATapi/utils/plotting.py
- tests/test_plotting.py
Adds a class to facilitate a blit plot in RasCAL, this class can be tested as shown below. The object creation should do a normal plot then subsequent updates will use blitting if the background has not changed. This leads to a decent speed up between the first draw and subsequent draws.
```
class TestPlot:
def __init__(self, block=False):
self.block = block
self.closed = False
self.blit_plot = None
def __enter__(self):
self.figure = plt.subplots(1, 2)[0]
self.figure.canvas.mpl_connect("close_event", self._setCloseState)
self.figure.show()
RATapi.events.register(RATapi.events.EventTypes.Plot, self.plotEvent)
return self.figure
def _setCloseState(self, _):
self.closed = True
def plotEvent(self, event):
if not self.closed and self.figure.number in plt.get_fignums():
if self.blit_plot is …
```
> Adds blitting plot

- RATapi/inputs.py
- tests/test_inputs.py
> Adds checks for undefined fields in layers and contrasts

- RATapi/__init__.py
- RATapi/outputs.py
- RATapi/project.py
- tests/test_outputs.py
- tests/utils.py
> Adds code to save and load results objects

- ratapi/utils/plotting.py
- tests/test_plotting.py
`shift_value` adjusts the spacing between the reflectivity plots in `plot_ref_sld`
> Adds the `shift_value` argument to `plot_ref_sld`

- .github/workflows/build_wheel.yml
- .github/workflows/run_ruff.yml
- .github/workflows/run_tests.yml
- pyproject.toml
- ratapi/controls.py
- ratapi/examples/domains/domains_XY_model.py
- ratapi/examples/normal_reflectivity/custom_XY_DSPC.py
- ratapi/utils/plotting.py
- setup.py
- tests/test_controls.py
- tests/test_plotting.py
Unify save method in controls to be like project and result
Refactors plotting to address https://github.com/RascalSoftware/RasCAL-2/issues/121
Enables openmp for windows
> Unify save methods

- .github/workflows/build_wheel.yml
- ratapi/utils/plotting.py
- An incorrect GLIBC version issue was experienced on IDAaas, this is fixed by setting Many Linux image
- Now that diagnostic and posterior plot will be updated simultaneously, I added progress callbacks to ensure the UI does not hang
> Fixes GLIBC Linux wheel issue and adds more progress callbacks
